PROJECT_REPO_URL = r"https://github.com/pitkwiecien/GitEasyClasses.git"
PROJECT_REPO_LOCATION = r"/Users/piotrkwiecien/desktop/hackathon/proj1-src/GitEasyClasses"
PINECONE_CODE_INDEX_NAME = "code-index"
PINECONE_FILES_INDEX_NAME = "file-index"
DOCS_FOLDER_NAME = "/.ai_docs"
