import os
from langchain.memory import ConversationBufferMemory, MongoDBChatMessageHistory


class MongoManager:
    """
    A class to manage interactions with MongoDB for storing chat message history.

    Attributes:
    - session_id (str): The session identifier.
    - api_key (str): The API key or connection string for MongoDB.
    - message_history (MongoDBChatMessageHistory): Instance to manage chat message history in MongoDB.
    """

    def __init__(self, session_id, api_key):
        """
        Initializes MongoManager with session_id and api_key, and creates an instance of MongoDBChatMessageHistory.

        Args:
        - session_id (str): The session identifier.
        - api_key (str): The API key or connection string for MongoDB.
        """
        self.session_id = session_id
        self.api_key = api_key
        self.message_history = MongoDBChatMessageHistory(
            connection_string=api_key,
            session_id=self.session_id
        )

    def add_message_to_Mongo(self, user_message, ai_message):
        """
        Adds user and AI messages to the MongoDB chat message history.

        Args:
        - user_message (str): The message sent by the user.
        - ai_message (str): The response generated by the AI.
        """
        self.message_history.add_user_message(user_message)
        self.message_history.add_ai_message(ai_message)
